name: Production Firebase Deployment & Lighthouse Audit
on:
  push:
    branches:
      - 'master'
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Site
        run: npm run generate
      - name: Optimize SVGs
        run: sudo npm install -g svgo && svgo -r ./dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: nfrost-dev
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/lighthouserc.json"
          temporaryPublicStorage: true
          runs: 1
          urls: |
            https://www.nfrost.dev/
